### ISSUE TITLE
Install from github does not copy resources. No manifest?

### ISSUE THREAD

**Issue by brooks-eco** [ckan/ckanext-excelforms#5]
CKAN 2.11

Installed ckanext-excelforms from github using 

```
. /usr/lib/ckan/default/bin/activate
cd /usr/lib/ckan/default/src/ckan
sudo /usr/lib/ckan/default/bin/python3.12 -m pip install 'git+https://github.com/ckan/ckanext-excelforms#egg=ckanext-excelforms'
```

The scripts in the root were installed however the resource folders were not copied into the destination -  no errors when rebooting with the excelforms plugin loaded however also no functionality 😁

missing folders
> ckanext-excelforms\assets
> ckanext-excelforms\i18n
> ckanext-excelforms\templates
> ckanext-excelforms\tests

Copying the folders in from the source zip got the plugin operational.  I see there is no manifest file in the plugin source folder - perhaps this is why.

**Comment by wardi** [comment]
@brooks-eco thank you! I think it's normal to exclude tests but the rest of the files should be there for sure.  Would you try it again now?
